### ISSUE TITLE
Finance home Page

### ISSUE THREAD

**Issue by Tsatsi** [Tsatsi/ThoughtWorksInternalFinanceProject#1]

**Comment by Tsatsi** [comment]
### Narrative

**As a *\* Finance guy 
**I want** to view the finance home page
**So That** I can begin using the system

### Acceptance Criteria

I enter a URL
- [ ] I am taken to a finance home page

## Tech Tasks

**Comment by simphiwes** [comment]
URL: http://localhost:8000/#/upload
