### ISSUE TITLE
Percentage and currency

### ISSUE THREAD

**Issue by Fez02** [Tsatsi/ThoughtWorksInternalFinanceProject#15]
Adding percentage and currency signs

**Comment by Fez02** [comment]
As a finance guy I want to be able to see the percentage and currency signs so that clarity is created for anyone that reads the information.

**Comment by simphiwes** [comment]
I see there are currency signs i just dont see any percentage signs, please advise if i am misunderstanding the requirement above

**Comment by MUSABALOYI-zz** [comment]
They are already showing. Must have been some other fault that hid them but whatever it was it has been resolved. Maybe we should try and see if we can reproduce this bug.
