### ISSUE TITLE
Kampala  financials

### ISSUE THREAD

**Issue by Liandra** [Tsatsi/ThoughtWorksInternalFinanceProject#4]
## Narrative

**As a** Finance guy 
**I want *\* view the Joburg planned and actuals 
**So That** I know the difference between the planned and actuals 
## Acceptance Criteria

I have successfully uploaded a excel file with the following sheets
IS-ZA-Actuals
and I am on the Financial tool page 
- [ ] There is a table called Johannesburg
- [ ] With column names Serial No, Description, [Current Month]' [Year], [Current Month]' [Year] Plan
- [ ] The Serial No column has a auto increment number
- [ ] The Description column has Revenue, Cost of Services, Gross Profit, Total OPEX, NOI, CGM%, Average Bill Rate, Average Utilization
- [ ] The planned column contains the following from the "IS-UG-Actuals" sheet for the CURRENT month
  - [ ] "Net Revenue"
  - [ ] "Total Cost Of Service"
  - [ ] "Gross Profit %"
  - [ ] "Total Operating Expense"
  - [ ]"Operating Contribution"
  - [ ] "Client Gross Margin %"
- [ ] The planned column contains the following from the "IS-UG-Plan" sheet for the CURRENT month
  - [ ] "Net Revenue"
  - [ ] "Total Cost Of Service"
  - [ ]"Gross Profit %"
  - [ ] "Total Operating Expense"
  - [ ]"Operating Contribution"
  - [ ] "Client Gross Margin %"
- [ ] The Average Bill rates Actuals is an input field which takes a two digit number 
- [ ] The Average Bill rates Pan is an input field which takes a two digit number 
- [ ] The Average Utilization Actuals is an input field which takes a two digit number 
- [ ] The Average Utilization Pan is an input field which takes a two digit number

**Comment by simphiwes** [comment]
As mentioned in bug #22 there is a column missing in the JHB financials table for Year.

Please advise.
